
DROP TABLE IF EXISTS customer cascade ;
DROP TABLE IF EXISTS application;

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS "role";
DROP TABLE IF EXISTS "user";

CREATE TABLE customer(
                         id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         identityno     VARCHAR(11) UNIQUE NOT NULL,
                         firstname VARCHAR(25)   NOT NULL,
                         lastname  VARCHAR(25)   NOT NULL,
                         salary    INT NOT NULL,
                         phone     VARCHAR(15)
);

INSERT INTO customer(identityno, firstname, lastname, salary, phone)
VALUES ('44444444444', 'Emre', 'Kaya', 15000, '905554443322'),
       ('44444744444', 'Aslı', 'Emel', 7000, '905554443322'),
       ('44444442444', 'Aytug', 'Kara', 4500, '905554443322');

CREATE TABLE application
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_limit INT NOT NULL,
    credit_result   VARCHAR(20) NOT NULL,
    customer_id   INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer (id)
);

INSERT INTO application(credit_limit, credit_result, customer_id)
VALUES (20000,'CONFIRMED',1),
       (20000,'CONFIRMED',2),
       (10000,'CONFIRMED',3);

CREATE TABLE "user"
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) UNIQUE NOT NULL,
    password VARCHAR(255)       NOT NULL
);

CREATE TABLE "role"
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(10) UNIQUE NOT NULL
);

INSERT INTO "role" (role_name)
VALUES ('ROLE_ADMIN');
INSERT INTO "role" (role_name)
VALUES ('ROLE_USER');

CREATE TABLE user_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);
